name: SonarCloud Scan

on:
  push:
  pull_request:

permissions:
  contents: read

concurrency:
  group: sonar-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sonarcloud:
    if: github.actor != 'dependabot[bot]'
    name: SonarQube Cloud Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarQube Cloud Scan
        uses: SonarSource/sonarqube-scan-action@v8
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
