name: SonarCloud Scan

on:
  push:
  pull_request:

permissions:
  contents: read

concurrency:
  group: sonar-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sonarcloud:
    if: github.actor != 'dependabot[bot]'
    name: SonarQube Cloud Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          fetch-depth: 0
      - name: SonarQube Cloud Scan
        uses: SonarSource/sonarqube-scan-action@22918119ff8e1ca75a623e15c8296b6ea4fbe28f # v8.2.1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
